[theme]
primaryColor="#6C63FF"
backgroundColor="#D9B0A7"
secondaryBackgroundColor="#F0F2F6"
textColor="#000000"
[[theme.fontFaces]]
family="noto-sans"
url="app/static/NotoSans-Italic-VariableFont_wdth,wght.ttf"
style="italic"
