[theme]
primaryColor="#6C63FF"
backgroundColor="#D9B0A7"
secondaryBackgroundColor="#F0F2F6"
textColor="#000000"
font="serif"
[[theme.fontFaces]]
family = "Times New Roman"
style = "italic"
url = "app/static/TimesNewRoman-Italic.ttf"
