[theme]
primaryColor="#6C63FF"
backgroundColor="#D9B0A7"
secondaryBackgroundColor="#F0F2F6"
textColor="#000000"
font="serif"
[[theme.fontFaces]]
family = "Arial"
style = "italic"
weight = 700
url = "app/static/Arial-BoldItalic.ttf"
